version: '3.9'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: cloudservice-db
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'YourStrong!Passw0rd'
    ports:
      - '1433:1433'
    volumes:
      - sqlvolume:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: cloudservice-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: 'Server=db,1433;Database=CloudServiceDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;'
    ports:
      - '5154:8080'
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: cloudservice-frontend
    environment:
      NEXT_PUBLIC_API_URL: 'http://localhost:5154'
    ports:
      - '3000:3000'
    depends_on:
      - api

volumes:
  sqlvolume:
