// <auto-generated />
using System;
using CloudService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CloudService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260802162535_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CloudService.Domain.Entities.AffiliateApplication", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("InternalNote")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("New");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("WebsiteOrChannel")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id")
                        .HasName("PK_AffiliateApplications");

                    b.HasIndex("Status", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_AffiliateApplications_Status_CreatedAt");

                    b.ToTable("AffiliateApplications", null, t =>
                        {
                            t.HasCheckConstraint("CK_AffiliateApplications_Status", "[Status] IN ('New', 'Processing', 'Done', 'Rejected')");
                        });
                });

            modelBuilder.Entity("CloudService.Domain.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_AppUsers");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_AppUsers_Email");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("UQ_AppUsers_UserName");

                    b.ToTable("AppUsers", (string)null);
                });

            modelBuilder.Entity("CloudService.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntityName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_AuditLogs");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_AuditLogs_UserId_CreatedAt");

                    b.HasIndex("EntityName", "EntityId", "CreatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_AuditLogs_Entity");

                    b.ToTable("AuditLogs", null, t =>
                        {
                            t.HasCheckConstraint("CK_AuditLogs_NewValuesJson", "[NewValues] IS NULL OR ISJSON([NewValues]) = 1");

                            t.HasCheckConstraint("CK_AuditLogs_OldValuesJson", "[OldValues] IS NULL OR ISJSON([OldValues]) = 1");
                        });
                });

            modelBuilder.Entity("CloudService.Domain.Entities.ContactRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("New");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(0)");

                    b.HasKey("Id")
                        .HasName("PK_ContactRequests");

                    b.HasIndex("Status", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_ContactRequests_Status_CreatedAt");

                    b.ToTable("ContactRequests", null, t =>
                        {
                            t.HasCheckConstraint("CK_ContactRequests_Status", "[Status] IN ('New', 'Read', 'Replied')");
                        });
                });

            modelBuilder.Entity("CloudService.Domain.Entities.NewsArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("varchar(280)");

                    b.Property<string>("Summary")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id")
                        .HasName("PK_NewsArticles");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("UQ_NewsArticles_Slug");

                    b.HasIndex("CategoryId", "IsPublished", "PublishedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_NewsArticles_Category_Published");

                    b.ToTable("NewsArticles", null, t =>
                        {
                            t.HasCheckConstraint("CK_NewsArticles_PublishDate", "[IsPublished] = 0 OR [PublishedAt] IS NOT NULL");

                            t.HasCheckConstraint("CK_NewsArticles_ViewCount", "[ViewCount] >= 0");
                        });
                });

            modelBuilder.Entity("CloudService.Domain.Entities.NewsCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id")
                        .HasName("PK_NewsCategories");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("UQ_NewsCategories_Slug");

                    b.ToTable("NewsCategories", (string)null);
                });

            modelBuilder.Entity("CloudService.Domain.Entities.OrderRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BillingCycleSnapshot")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("DiscountAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("EstimatedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("InternalNote")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PlanNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("PlanPriceId")
                        .HasColumnType("int");

                    b.Property<string>("PromotionCode")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ServicePlanId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("New");

                    b.Property<string>("TrackingCode")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(0)");

                    b.HasKey("Id")
                        .HasName("PK_OrderRequests");

                    b.HasIndex("PlanPriceId");

                    b.HasIndex("ServicePlanId")
                        .HasDatabaseName("IX_OrderRequests_ServicePlanId");

                    b.HasIndex("TrackingCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_OrderRequests_TrackingCode");

                    b.HasIndex("Status", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_OrderRequests_Status_CreatedAt");

                    b.ToTable("OrderRequests", null, t =>
                        {
                            t.HasCheckConstraint("CK_OrderRequests_Amounts", "[UnitPrice] >= 0 AND [DiscountAmount] >= 0 AND [EstimatedAmount] >= 0 AND [DiscountAmount] <= [UnitPrice]");

                            t.HasCheckConstraint("CK_OrderRequests_BillingCycle", "[BillingCycleSnapshot] IN ('Monthly', 'Quarterly', 'Yearly')");

                            t.HasCheckConstraint("CK_OrderRequests_Status", "[Status] IN ('New', 'Processing', 'Done', 'Rejected')");
                        });
                });

            modelBuilder.Entity("CloudService.Domain.Entities.PlanPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(3)")
                        .HasDefaultValue("VND");

                    b.Property<DateTime?>("EffectiveFrom")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2(0)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("OriginalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SalePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ServicePlanId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(0)");

                    b.HasKey("Id")
                        .HasName("PK_PlanPrices");

                    b.HasIndex("ServicePlanId", "IsActive")
                        .HasDatabaseName("IX_PlanPrices_Plan_Active");

                    b.HasIndex("ServicePlanId", "BillingCycle", "EffectiveFrom")
                        .IsUnique()
                        .HasDatabaseName("UQ_PlanPrices_Plan_Cycle_From")
                        .HasFilter("[EffectiveFrom] IS NOT NULL");

                    b.ToTable("PlanPrices", null, t =>
                        {
                            t.HasCheckConstraint("CK_PlanPrices_BillingCycle", "[BillingCycle] IN ('Monthly', 'Quarterly', 'Yearly')");

                            t.HasCheckConstraint("CK_PlanPrices_EffectiveRange", "[EffectiveTo] IS NULL OR [EffectiveFrom] IS NULL OR [EffectiveTo] > [EffectiveFrom]");

                            t.HasCheckConstraint("CK_PlanPrices_OriginalPrice", "[OriginalPrice] >= 0");

                            t.HasCheckConstraint("CK_PlanPrices_SalePrice", "[SalePrice] IS NULL OR ([SalePrice] >= 0 AND [SalePrice] <= [OriginalPrice])");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BillingCycle = "Monthly",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "VND",
                            IsActive = true,
                            OriginalPrice = 590000m,
                            SalePrice = 490000m,
                            ServicePlanId = 1
                        },
                        new
                        {
                            Id = 2,
                            BillingCycle = "Yearly",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "VND",
                            IsActive = true,
                            OriginalPrice = 7080000m,
                            SalePrice = 5880000m,
                            ServicePlanId = 1
                        },
                        new
                        {
                            Id = 3,
                            BillingCycle = "Monthly",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "VND",
                            IsActive = true,
                            OriginalPrice = 199000m,
                            SalePrice = 159000m,
                            ServicePlanId = 2
                        },
                        new
                        {
                            Id = 4,
                            BillingCycle = "Yearly",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "VND",
                            IsActive = true,
                            OriginalPrice = 2388000m,
                            SalePrice = 1908000m,
                            ServicePlanId = 2
                        });
                });

            modelBuilder.Entity("CloudService.Domain.Entities.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("DiscountValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("UsageLimit")
                        .HasColumnType("int");

                    b.Property<int>("UsedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id")
                        .HasName("PK_Promotions");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Promotions_Code");

                    b.ToTable("Promotions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Promotions_DateRange", "[EndAt] > [StartAt]");

                            t.HasCheckConstraint("CK_Promotions_DiscountType", "[DiscountType] IN ('Percentage', 'FixedAmount')");

                            t.HasCheckConstraint("CK_Promotions_DiscountValue", "[DiscountValue] > 0");

                            t.HasCheckConstraint("CK_Promotions_Percentage", "[DiscountType] <> 'Percentage' OR [DiscountValue] <= 100");

                            t.HasCheckConstraint("CK_Promotions_Usage", "[UsedCount] >= 0 AND ([UsageLimit] IS NULL OR ([UsageLimit] > 0 AND [UsedCount] <= [UsageLimit]))");
                        });
                });

            modelBuilder.Entity("CloudService.Domain.Entities.PromotionServicePlan", b =>
                {
                    b.Property<int>("PromotionId")
                        .HasColumnType("int");

                    b.Property<int>("ServicePlanId")
                        .HasColumnType("int");

                    b.HasKey("PromotionId", "ServicePlanId")
                        .HasName("PK_PromotionServicePlans");

                    b.HasIndex("ServicePlanId");

                    b.ToTable("PromotionServicePlans", (string)null);
                });

            modelBuilder.Entity("CloudService.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("varchar(45)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("JwtId")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ReplacedByHash")
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_RefreshTokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("UQ_RefreshTokens_TokenHash");

                    b.HasIndex("UserId", "ExpiresAt")
                        .HasDatabaseName("IX_RefreshTokens_UserId_ExpiresAt");

                    b.ToTable("RefreshTokens", null, t =>
                        {
                            t.HasCheckConstraint("CK_RefreshTokens_ExpiresAt", "[ExpiresAt] > [CreatedAt]");
                        });
                });

            modelBuilder.Entity("CloudService.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_Roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_Roles_Name");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Toàn quyền quản trị hệ thống",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Quản lý nội dung và xử lý yêu cầu",
                            Name = "Editor"
                        });
                });

            modelBuilder.Entity("CloudService.Domain.Entities.ServiceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Icon")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("varchar(120)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(0)");

                    b.HasKey("Id")
                        .HasName("PK_ServiceCategories");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("UQ_ServiceCategories_Slug");

                    b.ToTable("ServiceCategories", null, t =>
                        {
                            t.HasCheckConstraint("CK_ServiceCategories_DisplayOrder", "[DisplayOrder] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Máy chủ ảo hiệu năng cao",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "VPS",
                            Slug = "vps"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dịch vụ lưu trữ website",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Hosting",
                            Slug = "hosting"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Đăng ký và quản lý tên miền",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Domain",
                            Slug = "domain"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Email theo tên miền doanh nghiệp",
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "Email doanh nghiệp",
                            Slug = "business-email"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Chứng chỉ bảo mật website",
                            DisplayOrder = 5,
                            IsActive = true,
                            Name = "SSL",
                            Slug = "ssl"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Giải pháp bảo vệ hạ tầng trước tấn công DDoS",
                            DisplayOrder = 6,
                            IsActive = true,
                            Name = "Firewall chống DDoS",
                            Slug = "ddos-firewall"
                        });
                });

            modelBuilder.Entity("CloudService.Domain.Entities.ServicePlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BandwidthGb")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("CpuCores")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("QrCodePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("QrGeneratedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("QrTargetUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("RamGb")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("varchar(180)");

                    b.Property<string>("SpecificationsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StorageGb")
                        .HasColumnType("int");

                    b.Property<string>("StorageType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(0)");

                    b.HasKey("Id")
                        .HasName("PK_ServicePlans");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("UQ_ServicePlans_Slug");

                    b.HasIndex("CategoryId", "IsActive")
                        .HasDatabaseName("IX_ServicePlans_CategoryId_IsActive");

                    b.ToTable("ServicePlans", null, t =>
                        {
                            t.HasCheckConstraint("CK_ServicePlans_BandwidthGb", "[BandwidthGb] IS NULL OR [BandwidthGb] > 0");

                            t.HasCheckConstraint("CK_ServicePlans_CpuCores", "[CpuCores] IS NULL OR [CpuCores] > 0");

                            t.HasCheckConstraint("CK_ServicePlans_DisplayOrder", "[DisplayOrder] >= 0");

                            t.HasCheckConstraint("CK_ServicePlans_RamGb", "[RamGb] IS NULL OR [RamGb] > 0");

                            t.HasCheckConstraint("CK_ServicePlans_SpecificationsJson", "[SpecificationsJson] IS NULL OR ISJSON([SpecificationsJson]) = 1");

                            t.HasCheckConstraint("CK_ServicePlans_StorageGb", "[StorageGb] IS NULL OR [StorageGb] > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BandwidthGb = 2000,
                            CategoryId = 1,
                            CpuCores = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Cloud VPS Basic",
                            RamGb = 2m,
                            ShortDescription = "Gói VPS phù hợp website và ứng dụng nhỏ",
                            Slug = "cloud-vps-basic",
                            SpecificationsJson = "{\"IPv4\":1,\"Backup\":\"Weekly\",\"Uptime\":\"99.9%\"}",
                            StorageGb = 40,
                            StorageType = "NVMe"
                        },
                        new
                        {
                            Id = 2,
                            BandwidthGb = 1000,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Business Hosting",
                            ShortDescription = "Hosting cho website doanh nghiệp",
                            Slug = "business-hosting",
                            SpecificationsJson = "{\"Websites\":5,\"EmailAccounts\":20,\"SSL\":\"Included\"}",
                            StorageGb = 20,
                            StorageType = "NVMe"
                        });
                });

            modelBuilder.Entity("CloudService.Domain.Entities.Testimonial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)5);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(0)");

                    b.HasKey("Id")
                        .HasName("PK_Testimonials");

                    b.ToTable("Testimonials", null, t =>
                        {
                            t.HasCheckConstraint("CK_Testimonials_DisplayOrder", "[DisplayOrder] >= 0");

                            t.HasCheckConstraint("CK_Testimonials_Rating", "[Rating] BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("CloudService.Domain.Entities.AppUser", b =>
                {
                    b.HasOne("CloudService.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_AppUsers_Roles");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CloudService.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("CloudService.Domain.Entities.AppUser", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_AuditLogs_AppUsers");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CloudService.Domain.Entities.NewsArticle", b =>
                {
                    b.HasOne("CloudService.Domain.Entities.NewsCategory", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_NewsArticles_NewsCategories");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CloudService.Domain.Entities.OrderRequest", b =>
                {
                    b.HasOne("CloudService.Domain.Entities.PlanPrice", "PlanPrice")
                        .WithMany("OrderRequests")
                        .HasForeignKey("PlanPriceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_OrderRequests_PlanPrices");

                    b.HasOne("CloudService.Domain.Entities.ServicePlan", "ServicePlan")
                        .WithMany("OrderRequests")
                        .HasForeignKey("ServicePlanId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_OrderRequests_ServicePlans");

                    b.Navigation("PlanPrice");

                    b.Navigation("ServicePlan");
                });

            modelBuilder.Entity("CloudService.Domain.Entities.PlanPrice", b =>
                {
                    b.HasOne("CloudService.Domain.Entities.ServicePlan", "ServicePlan")
                        .WithMany("Prices")
                        .HasForeignKey("ServicePlanId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_PlanPrices_ServicePlans");

                    b.Navigation("ServicePlan");
                });

            modelBuilder.Entity("CloudService.Domain.Entities.PromotionServicePlan", b =>
                {
                    b.HasOne("CloudService.Domain.Entities.Promotion", "Promotion")
                        .WithMany("PromotionServicePlans")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PromotionServicePlans_Promotions");

                    b.HasOne("CloudService.Domain.Entities.ServicePlan", "ServicePlan")
                        .WithMany("PromotionServicePlans")
                        .HasForeignKey("ServicePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PromotionServicePlans_ServicePlans");

                    b.Navigation("Promotion");

                    b.Navigation("ServicePlan");
                });

            modelBuilder.Entity("CloudService.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("CloudService.Domain.Entities.AppUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_RefreshTokens_AppUsers");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CloudService.Domain.Entities.ServicePlan", b =>
                {
                    b.HasOne("CloudService.Domain.Entities.ServiceCategory", "Category")
                        .WithMany("ServicePlans")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_ServicePlans_ServiceCategories");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CloudService.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("CloudService.Domain.Entities.NewsCategory", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("CloudService.Domain.Entities.PlanPrice", b =>
                {
                    b.Navigation("OrderRequests");
                });

            modelBuilder.Entity("CloudService.Domain.Entities.Promotion", b =>
                {
                    b.Navigation("PromotionServicePlans");
                });

            modelBuilder.Entity("CloudService.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CloudService.Domain.Entities.ServiceCategory", b =>
                {
                    b.Navigation("ServicePlans");
                });

            modelBuilder.Entity("CloudService.Domain.Entities.ServicePlan", b =>
                {
                    b.Navigation("OrderRequests");

                    b.Navigation("Prices");

                    b.Navigation("PromotionServicePlans");
                });
#pragma warning restore 612, 618
        }
    }
}
